package dev.shanuka.thesweetcupcakeshop.view.panels.dashboard.dialogs;

import dev.shanuka.thesweetcupcakeshop.exception.ApplicationError;
import dev.shanuka.thesweetcupcakeshop.exception.DuplicateEntryError;
import dev.shanuka.thesweetcupcakeshop.service.InventoryService;
import dev.shanuka.thesweetcupcakeshop.util.Messages;
import dev.shanuka.thesweetcupcakeshop.util.PlaceholderManager;

/**
 * Add new categpru dialog for the Categories Panel
 *
 * @author Shanuka
 */
public class AddCategoryDialog extends javax.swing.JPanel {
    // Function that closes this dialog and refreshes items list in the parent
    Runnable action;
    
    /**
     * Creates new form AddCategoryDialog
     * 
     * param action Action to run once the "Add Category" button has clicked
     */
    public AddCategoryDialog(Runnable action) {
        this.action = action;
        
        // Focus the main panel first
        this.setFocusable(true);
        this.requestFocus();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogTitle = new javax.swing.JLabel();
        itemNameTitle = new javax.swing.JLabel();
        itemNamePanel = new javax.swing.JPanel();
        categoryNameInput = new javax.swing.JTextField();
        addCategoryBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 244, 244));

        dialogTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        dialogTitle.setForeground(new java.awt.Color(66, 66, 66));
        dialogTitle.setText("Add New Category");

        itemNameTitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        itemNameTitle.setForeground(new java.awt.Color(66, 66, 66));
        itemNameTitle.setText("Category name");

        itemNamePanel.setBackground(new java.awt.Color(255, 255, 255));
        itemNamePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        itemNamePanel.setName("itemNamePanel"); // NOI18N
        itemNamePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemNamePanelMouseClicked(evt);
            }
        });

        categoryNameInput.setBackground(new java.awt.Color(255, 255, 255));
        categoryNameInput.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        categoryNameInput.setForeground(new java.awt.Color(113, 113, 113));
        categoryNameInput.setText("Category name");
        categoryNameInput.setBorder(null);
        categoryNameInput.setName("categoryNameInput"); // NOI18N
        categoryNameInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                categoryNameInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                categoryNameInputFocusLost(evt);
            }
        });

        javax.swing.GroupLayout itemNamePanelLayout = new javax.swing.GroupLayout(itemNamePanel);
        itemNamePanel.setLayout(itemNamePanelLayout);
        itemNamePanelLayout.setHorizontalGroup(
            itemNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemNamePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(categoryNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemNamePanelLayout.setVerticalGroup(
            itemNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemNamePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(categoryNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        addCategoryBtn.setBackground(new java.awt.Color(97, 11, 21));
        addCategoryBtn.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        addCategoryBtn.setForeground(new java.awt.Color(204,204,204)
        );
        addCategoryBtn.setText("Add Category");
        addCategoryBtn.setBorder(null);
        addCategoryBtn.setMaximumSize(new java.awt.Dimension(52, 52));
        addCategoryBtn.setMinimumSize(new java.awt.Dimension(52, 52));
        addCategoryBtn.setPreferredSize(new java.awt.Dimension(52, 52));
        addCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addCategoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemNameTitle)
                    .addComponent(dialogTitle)
                    .addComponent(itemNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(dialogTitle)
                .addGap(39, 39, 39)
                .addComponent(itemNameTitle)
                .addGap(18, 18, 18)
                .addComponent(itemNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(addCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void itemNamePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemNamePanelMouseClicked
        categoryNameInput.requestFocus(); // Focus item name input
    }//GEN-LAST:event_itemNamePanelMouseClicked

    // Event: Add category button has been clicked
    private void addCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoryBtnActionPerformed
        String userInput = categoryNameInput.getText();
        
        // Abort and display an error message if user input is blank or placeholder
        if(userInput.isBlank() || PlaceholderManager.getPlaceholderFor(categoryNameInput.getName()).equalsIgnoreCase(userInput)) {
            Messages.showError(this, "Input Error", "Please enter a valid category name to continue");
            return;
        }
        
        try {
            // If user has entered a valid category name, add it as a new category
            InventoryService.addCategory(userInput);
        }
        
        catch (DuplicateEntryError e) {
            Messages.showError(this, "Duplicate Entry Error", "A category with the given name already exists");
        }
        
        catch (ApplicationError e) {
            Messages.showError(this, "Application Error", "An error has been occured while adding the new item");
        }

        // Run the action passed by the parent form
        action.run();
    }//GEN-LAST:event_addCategoryBtnActionPerformed

    // Event: Category name input has gained focus
    private void categoryNameInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_categoryNameInputFocusGained
        PlaceholderManager.removePlaceholder(categoryNameInput);
    }//GEN-LAST:event_categoryNameInputFocusGained

    // Event: Category name input has lost focus
    private void categoryNameInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_categoryNameInputFocusLost
        PlaceholderManager.addPlaceholder(categoryNameInput);
    }//GEN-LAST:event_categoryNameInputFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCategoryBtn;
    private javax.swing.JTextField categoryNameInput;
    private javax.swing.JLabel dialogTitle;
    private javax.swing.JPanel itemNamePanel;
    private javax.swing.JLabel itemNameTitle;
    // End of variables declaration//GEN-END:variables
}
