package dev.shanuka.thesweetcupcakeshop.view.panels.dashboard.dialogs;

import dev.shanuka.thesweetcupcakeshop.exception.ApplicationError;
import dev.shanuka.thesweetcupcakeshop.model.Item;
import dev.shanuka.thesweetcupcakeshop.service.InventoryService;
import dev.shanuka.thesweetcupcakeshop.util.Messages;
import dev.shanuka.thesweetcupcakeshop.util.PlaceholderManager;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JTextField;

/**
 * Add item dialog for the Inventory Panel
 *
 * @author Shanuka
 */
public class AddItemDialog extends javax.swing.JPanel {
    String itemName;
    Double itemPrice;
    
    // Function that closes this dialog and refreshes items list in the parent
    Runnable action;

    /**
     * Creates new form AddItemDialog
     *
     * @param action Action to run once the "Add Item" button has clicked
     */
    public AddItemDialog(Runnable action) {
        this.action = action;
        
        initComponents();

        // Initially focus the main panel
        this.setFocusable(true);
        this.requestFocus();
        
        // Add inputFocusListener to input fields for managing placeholders
        itemNameInput.addFocusListener(inputFocusListener);
        itemPriceInput.addFocusListener(inputFocusListener);
        
        try {
            // Update the categories list
            loadCategories();
        } catch (ApplicationError e) {
            Messages.showError(this, "Application Error", "An error has occured while loading the list of categories");
        }
    }

    // Focus listener for inputs
    private final FocusListener inputFocusListener = new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent evt) {
            onFocusGained(evt);
        }

        @Override
        public void focusLost(FocusEvent evt) {
            onFocusLost(evt);
        }
    };

    private void onFocusGained(FocusEvent evt) {
        Object source = evt.getSource();

        if (source instanceof JTextField field) {
            PlaceholderManager.removePlaceholder(field);
        }
    }

    private void onFocusLost(FocusEvent evt) {
        Object source = evt.getSource();

        if (source instanceof JTextField field) {
            PlaceholderManager.addPlaceholder(field);
        }
    }

    private boolean validateInputs() {
        // Check the item name
        if(itemNameInput.getText().isBlank() || PlaceholderManager.getPlaceholderFor(itemNameInput.getName()).equalsIgnoreCase(itemNameInput.getText())) {
            Messages.showError(this, "Input Error", "Please enter an item name to continue");
            return false;
        }
        
        // Check item price
        if(PlaceholderManager.getPlaceholderFor(itemPriceInput.getName()).equals(itemPriceInput.getText())) {
            Messages.showError(this, "Input Error", "Please enter an item price to continue");
            return false;
        }
        
        try {
            itemName = itemNameInput.getText();
            itemPrice = Double.parseDouble(itemPriceInput.getText());
            
            return true;
        } 
        
        catch (NumberFormatException e) {
            Messages.showError(this, "Input Error", "Please enter a valid item price to continue");
            
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUserButton = new javax.swing.JButton();
        dialogTitle = new javax.swing.JLabel();
        itemNameTitle = new javax.swing.JLabel();
        itemNamePanel = new javax.swing.JPanel();
        itemNameInput = new javax.swing.JTextField();
        itemPricePanel = new javax.swing.JPanel();
        itemPriceInput = new javax.swing.JTextField();
        currencyLabel = new javax.swing.JLabel();
        itemPriceLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        categoriesList = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(244, 244, 244));
        setPreferredSize(new java.awt.Dimension(722, 566));

        addUserButton.setBackground(new java.awt.Color(97, 11, 21));
        addUserButton.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        addUserButton.setForeground(new java.awt.Color(204,204,204)
        );
        addUserButton.setText("Add Item");
        addUserButton.setBorder(null);
        addUserButton.setMaximumSize(new java.awt.Dimension(52, 52));
        addUserButton.setMinimumSize(new java.awt.Dimension(52, 52));
        addUserButton.setPreferredSize(new java.awt.Dimension(52, 52));
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        dialogTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        dialogTitle.setForeground(new java.awt.Color(66, 66, 66));
        dialogTitle.setText("Add New Item");

        itemNameTitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        itemNameTitle.setForeground(new java.awt.Color(66, 66, 66));
        itemNameTitle.setText("Item name");

        itemNamePanel.setBackground(new java.awt.Color(255, 255, 255));
        itemNamePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        itemNamePanel.setName("itemNamePanel"); // NOI18N
        itemNamePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemNamePanelMouseClicked(evt);
            }
        });

        itemNameInput.setBackground(new java.awt.Color(255, 255, 255));
        itemNameInput.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        itemNameInput.setForeground(new java.awt.Color(113, 113, 113));
        itemNameInput.setText("Item name");
        itemNameInput.setBorder(null);
        itemNameInput.setName("itemNameInput"); // NOI18N

        javax.swing.GroupLayout itemNamePanelLayout = new javax.swing.GroupLayout(itemNamePanel);
        itemNamePanel.setLayout(itemNamePanelLayout);
        itemNamePanelLayout.setHorizontalGroup(
            itemNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemNamePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(itemNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemNamePanelLayout.setVerticalGroup(
            itemNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemNamePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(itemNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        itemPricePanel.setBackground(new java.awt.Color(255, 255, 255));
        itemPricePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        itemPricePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemPricePanelMouseClicked(evt);
            }
        });

        itemPriceInput.setBackground(new java.awt.Color(255, 255, 255));
        itemPriceInput.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        itemPriceInput.setForeground(new java.awt.Color(113, 113, 113));
        itemPriceInput.setText("0.00");
        itemPriceInput.setBorder(null);
        itemPriceInput.setName("itemPriceInput"); // NOI18N

        currencyLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        currencyLabel.setForeground(new java.awt.Color(113, 113, 113));
        currencyLabel.setText("Rs.");

        javax.swing.GroupLayout itemPricePanelLayout = new javax.swing.GroupLayout(itemPricePanel);
        itemPricePanel.setLayout(itemPricePanelLayout);
        itemPricePanelLayout.setHorizontalGroup(
            itemPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemPricePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(currencyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        itemPricePanelLayout.setVerticalGroup(
            itemPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPricePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(itemPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currencyLabel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        itemPriceLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        itemPriceLabel.setForeground(new java.awt.Color(66, 66, 66));
        itemPriceLabel.setText("Item Price");

        categoryLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(66, 66, 66));
        categoryLabel.setText("Category");

        categoriesList.setBackground(new java.awt.Color(255, 255, 255));
        categoriesList.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        categoriesList.setForeground(new java.awt.Color(113, 113, 113));
        categoriesList.setMaximumRowCount(1000);
        categoriesList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASHIER", "MANAGER" }));
        categoriesList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dialogTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(itemNamePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemPricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemPriceLabel)
                                    .addComponent(itemNameTitle))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(categoryLabel)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(categoriesList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(dialogTitle)
                .addGap(32, 32, 32)
                .addComponent(itemNameTitle)
                .addGap(18, 18, 18)
                .addComponent(itemNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemPriceLabel)
                    .addComponent(categoryLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(categoriesList)
                    .addComponent(itemPricePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadCategories() throws ApplicationError {
        // Fetch the list of category names
        List<String> categories = InventoryService.getAllCategories()
                .stream()
                .map(category -> category.getName())
                .collect(Collectors.toList());

        // Clear existing items in the combo box
        categoriesList.removeAllItems();

        // Add the new categories
        for (String categoryName : categories) {
            categoriesList.addItem(categoryName);
        }

        // Select the first item (if available)
        if (!categories.isEmpty()) {
            categoriesList.setSelectedIndex(0);
        }
    }

    // Event: When the add item button is being clicked
    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        if(!validateInputs()) return; // Continue only if all inputs are valid
        
        // Add the new item
        Item newItem = new Item();

        // Extract the selected category as a String
        String selectedCategory = categoriesList.getSelectedItem() != null 
            ? categoriesList.getSelectedItem().toString()
            : null;
        
        try {
            InventoryService.addItem(itemName, selectedCategory, itemPrice);
            Messages.showSuccess(this, "Item Added", "The new item has been added to the list of items successfully");
        }
        
        catch (ApplicationError e) {
            Messages.showError(this, "Application Error", "An error has been occured while adding the new item");
        }
        
        // Run the action passed by the parent form
        action.run();
    }//GEN-LAST:event_addUserButtonActionPerformed

    // Event: When anywhere within the item price panel is clicked
    private void itemPricePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemPricePanelMouseClicked
        itemPriceInput.requestFocus(); // Focus item price input
    }//GEN-LAST:event_itemPricePanelMouseClicked

    // Event: When anywhere within the item name panel is clicked
    private void itemNamePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemNamePanelMouseClicked
        itemNameInput.requestFocus(); // Focus item name input
    }//GEN-LAST:event_itemNamePanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JComboBox<String> categoriesList;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel currencyLabel;
    private javax.swing.JLabel dialogTitle;
    private javax.swing.JTextField itemNameInput;
    private javax.swing.JPanel itemNamePanel;
    private javax.swing.JLabel itemNameTitle;
    private javax.swing.JTextField itemPriceInput;
    private javax.swing.JLabel itemPriceLabel;
    private javax.swing.JPanel itemPricePanel;
    // End of variables declaration//GEN-END:variables
}
