package dev.shanuka.thesweetcupcakeshop.view.panels.dashboard.dialogs;

import dev.shanuka.thesweetcupcakeshop.enums.UserRole;
import dev.shanuka.thesweetcupcakeshop.exception.ApplicationError;
import dev.shanuka.thesweetcupcakeshop.model.User;
import dev.shanuka.thesweetcupcakeshop.service.UserService;
import dev.shanuka.thesweetcupcakeshop.util.Messages;
import dev.shanuka.thesweetcupcakeshop.util.PlaceholderManager;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JTextField;

/**
 * Add new user dialog for the user panel of manager dashboard
 *
 * @author Shanuka
 */
public class AddUserDialog extends javax.swing.JPanel {

    // Function that closes this dialog and refreshes users list in the parent
    Runnable action;

    // New user details
    private String firstName;
    private String lastName;

    /**
     * Creates new form AddUserPanel
     *
     * @param action Action to run once the "Add User" button has clicked
     */
    public AddUserDialog(Runnable action) {
        this.action = action;

        // Initially focus the main panel
        this.setFocusable(true);
        this.requestFocus();

        initComponents();

        // Add inputFocusListener to input fields for managing placeholders
        firstNameField.addFocusListener(inputFocusListener);
        lastNameField.addFocusListener(inputFocusListener);
        newEmailField.addFocusListener(inputFocusListener);
        newPasswordField.addFocusListener(inputFocusListener);
    }

    // Focus listener for inputs
    private final FocusListener inputFocusListener = new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent evt) {
            onFocusGained(evt);
        }

        @Override
        public void focusLost(FocusEvent evt) {
            onFocusLost(evt);
        }
    };

    private void onFocusGained(FocusEvent evt) {
        Object source = evt.getSource();

        if (source instanceof JTextField field) {
            PlaceholderManager.removePlaceholder(field);
        }
    }

    private void onFocusLost(FocusEvent evt) {
        Object source = evt.getSource();

        if (source instanceof JTextField field) {
            PlaceholderManager.addPlaceholder(field);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogTitle = new javax.swing.JLabel();
        firstNamePanel = new javax.swing.JPanel();
        firstNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        lastNamePanel = new javax.swing.JPanel();
        lastNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        newEmailPanel = new javax.swing.JPanel();
        newEmailField = new javax.swing.JTextField();
        emailAddressLabel = new javax.swing.JLabel();
        emailAddressLabel1 = new javax.swing.JLabel();
        newPasswordPanel = new javax.swing.JPanel();
        newPasswordField = new javax.swing.JTextField();
        emailAddressLabel2 = new javax.swing.JLabel();
        userRoleSelection = new javax.swing.JComboBox<>();
        addUserBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 244, 244));

        dialogTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        dialogTitle.setForeground(new java.awt.Color(66, 66, 66));
        dialogTitle.setText("Add New User");

        firstNamePanel.setBackground(new java.awt.Color(255, 255, 255));
        firstNamePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        firstNamePanel.setName("firstNamePanel"); // NOI18N

        firstNameField.setBackground(new java.awt.Color(255, 255, 255));
        firstNameField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        firstNameField.setForeground(new java.awt.Color(113, 113, 113));
        firstNameField.setText("First name");
        firstNameField.setBorder(null);
        firstNameField.setName("firstNameField"); // NOI18N

        javax.swing.GroupLayout firstNamePanelLayout = new javax.swing.GroupLayout(firstNamePanel);
        firstNamePanel.setLayout(firstNamePanelLayout);
        firstNamePanelLayout.setHorizontalGroup(
            firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstNamePanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        firstNamePanelLayout.setVerticalGroup(
            firstNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        firstNameLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(66, 66, 66));
        firstNameLabel.setText("First name");

        lastNamePanel.setBackground(new java.awt.Color(255, 255, 255));
        lastNamePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        lastNamePanel.setName("itemNamePanel"); // NOI18N

        lastNameField.setBackground(new java.awt.Color(255, 255, 255));
        lastNameField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lastNameField.setForeground(new java.awt.Color(113, 113, 113));
        lastNameField.setText("Last name");
        lastNameField.setBorder(null);
        lastNameField.setName("lastNameField"); // NOI18N

        javax.swing.GroupLayout lastNamePanelLayout = new javax.swing.GroupLayout(lastNamePanel);
        lastNamePanel.setLayout(lastNamePanelLayout);
        lastNamePanelLayout.setHorizontalGroup(
            lastNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lastNamePanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lastNamePanelLayout.setVerticalGroup(
            lastNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        lastNameLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(66, 66, 66));
        lastNameLabel.setText("Last name");

        newEmailPanel.setBackground(new java.awt.Color(255, 255, 255));
        newEmailPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        newEmailPanel.setName("itemNamePanel"); // NOI18N

        newEmailField.setBackground(new java.awt.Color(255, 255, 255));
        newEmailField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        newEmailField.setForeground(new java.awt.Color(113, 113, 113));
        newEmailField.setText("Email address");
        newEmailField.setBorder(null);
        newEmailField.setMargin(new java.awt.Insets(2, 20, 2, 6));
        newEmailField.setName("newEmailField"); // NOI18N

        javax.swing.GroupLayout newEmailPanelLayout = new javax.swing.GroupLayout(newEmailPanel);
        newEmailPanel.setLayout(newEmailPanelLayout);
        newEmailPanelLayout.setHorizontalGroup(
            newEmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newEmailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        newEmailPanelLayout.setVerticalGroup(
            newEmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newEmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        emailAddressLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        emailAddressLabel.setForeground(new java.awt.Color(66, 66, 66));
        emailAddressLabel.setText("Email address");

        emailAddressLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        emailAddressLabel1.setForeground(new java.awt.Color(66, 66, 66));
        emailAddressLabel1.setText("Password");

        newPasswordPanel.setBackground(new java.awt.Color(255, 255, 255));
        newPasswordPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        newPasswordPanel.setName("itemNamePanel"); // NOI18N

        newPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        newPasswordField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        newPasswordField.setForeground(new java.awt.Color(113, 113, 113));
        newPasswordField.setText("New Password");
        newPasswordField.setBorder(null);
        newPasswordField.setName("newPasswordField"); // NOI18N

        javax.swing.GroupLayout newPasswordPanelLayout = new javax.swing.GroupLayout(newPasswordPanel);
        newPasswordPanel.setLayout(newPasswordPanelLayout);
        newPasswordPanelLayout.setHorizontalGroup(
            newPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPasswordPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(newPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );
        newPasswordPanelLayout.setVerticalGroup(
            newPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newPasswordField)
        );

        emailAddressLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        emailAddressLabel2.setForeground(new java.awt.Color(66, 66, 66));
        emailAddressLabel2.setText("Role");

        userRoleSelection.setBackground(new java.awt.Color(255, 255, 255));
        userRoleSelection.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        userRoleSelection.setForeground(new java.awt.Color(113, 113, 113));
        userRoleSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASHIER", "MANAGER" }));
        userRoleSelection.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));

        addUserBtn.setBackground(new java.awt.Color(97, 11, 21));
        addUserBtn.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        addUserBtn.setForeground(new java.awt.Color(204,204,204)
        );
        addUserBtn.setText("Add User");
        addUserBtn.setBorder(null);
        addUserBtn.setMaximumSize(new java.awt.Dimension(52, 52));
        addUserBtn.setMinimumSize(new java.awt.Dimension(52, 52));
        addUserBtn.setPreferredSize(new java.awt.Dimension(52, 52));
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailAddressLabel)
                            .addComponent(dialogTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameLabel)
                                    .addComponent(firstNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameLabel)
                                    .addComponent(lastNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(newEmailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newPasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(userRoleSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(addUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailAddressLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailAddressLabel2)
                        .addGap(285, 285, 285))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lastNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lastNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dialogTitle)
                        .addGap(33, 33, 33)
                        .addComponent(firstNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(firstNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(emailAddressLabel)
                .addGap(18, 18, 18)
                .addComponent(newEmailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAddressLabel1)
                    .addComponent(emailAddressLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userRoleSelection, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(newPasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(addUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Validates the user input for a given text field.
     *
     * @param textField Text field to validate
     * @return true if the input is valid
     */
    private boolean isValid(JTextField textField) {
        String userInput = textField.getText().trim();
        String placeholder = PlaceholderManager.getPlaceholderFor(textField.getName());
        boolean containsText = !userInput.isBlank() && !placeholder.equalsIgnoreCase(userInput);

        // Input must not be empty or placeholder text
        if (!containsText) {
            Messages.showError(this, "Input Error", "Please fill the " + placeholder + " field");
            return false;
        }

        // Validte email field
        if (textField == newEmailField) {
            // Simple but effective email regex
            boolean validEmail = userInput.matches("^[\\w._%+-]+@[\\w.-]+\\.[A-Za-z]{2,}$");

            if (!validEmail) {
                Messages.showError(this, "Invalid Email", "Please enter a valid email address (e.g. johndoe@gmail.com)");
                return false;
            }

            return true;
        }

        // Validate password field (minimum 8 chars, 1 letter and 1 number)
        if (textField == newPasswordField) {
            boolean validPassword = userInput.matches("^(?=.*[A-Za-z])(?=.*\\d).{8,}$");

            if (!validPassword) {
                Messages.showError(this, "Weak Password", "Password must be at least 8 characters long and include both letters and numbers");
                
                return false;
            }

            return true;
        }
        
        return true; // If no input issues were found
    }

    // Event: Add user button has been clicked
    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        // Abort if any of the input errors have occured
        if(!isValid(firstNameField) || !isValid(lastNameField) || !isValid(newEmailField) || !isValid(newPasswordField)) return;
        
        try {
            UserService.addUser(
                    UserRole.valueOf(userRoleSelection.getSelectedItem().toString()), 
                    firstNameField.getText(), 
                    lastNameField.getText(), 
                    newEmailField.getText(), 
                    newPasswordField.getText());
        
            // Show a success message
            Messages.showSuccess(this, "Registration Complete", "The user has been added and can now log in with their credentials.");

            
            // Refresh the list of users on parent panel
            action.run();
        }
        
        catch(ApplicationError | IllegalArgumentException ex) {
            Messages.showError(this, "Registration Error", "An error has been occured while processing your registration request");
        }
    }//GEN-LAST:event_addUserBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserBtn;
    private javax.swing.JLabel dialogTitle;
    private javax.swing.JLabel emailAddressLabel;
    private javax.swing.JLabel emailAddressLabel1;
    private javax.swing.JLabel emailAddressLabel2;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JPanel firstNamePanel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPanel lastNamePanel;
    private javax.swing.JTextField newEmailField;
    private javax.swing.JPanel newEmailPanel;
    private javax.swing.JTextField newPasswordField;
    private javax.swing.JPanel newPasswordPanel;
    private javax.swing.JComboBox<String> userRoleSelection;
    // End of variables declaration//GEN-END:variables
}
