package dev.shanuka.thesweetcupcakeshop.view.panels.dashboard.dialogs;

import dev.shanuka.thesweetcupcakeshop.exception.ApplicationError;
import dev.shanuka.thesweetcupcakeshop.model.Item;
import dev.shanuka.thesweetcupcakeshop.model.Order;
import dev.shanuka.thesweetcupcakeshop.service.OrderService;
import static dev.shanuka.thesweetcupcakeshop.service.OrderService.getAllOrders;
import dev.shanuka.thesweetcupcakeshop.util.AppConstants;
import dev.shanuka.thesweetcupcakeshop.util.Helpers;
import dev.shanuka.thesweetcupcakeshop.util.Messages;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * Modal dialog for recording an order
 *
 * @author Shanuka
 */
public class RecordSaleDialog extends javax.swing.JPanel {
    // Parent frame in which the current panel is mounted
    JFrame parentFrame;
    
    // Action to record a sale
    Runnable recordSale;
    
    private Integer newOrderId;
    private Item orderItem;
    private Integer orderQuantity = 1;
    
    private void setOrderQuantity(Integer quantity) {
        // Update value (minimum: 1)
        orderQuantity = quantity < 1 ? 1 : quantity;

        // Update quantity label
        orderQuantityInput.setText(orderQuantity.toString());
        
        // Update total amount
        setTotalAmount();
    }

    private void setOrderItem(Item item) {
        this.orderItem = item;
        
        // Update total amount
        setTotalAmount();
        
        // Update item name and text color for the item name label
        productName.setText(item.getName());
        productName.setForeground(new Color(114,114,114));
    }
    
    private void setTotalAmount() {
        if(orderItem == null) return;
        
        // Total amount = Item price * Quantity
        totalAmountLabel.setText(AppConstants.CURRENCY_FORMAT.format(orderItem.getPrice() * orderQuantity));
    }

    /**
     * Creates new form RecordSaleDialog
     */
    public RecordSaleDialog(JFrame parentFrame, Runnable recordSale) {
        initComponents();
        
        this.parentFrame = parentFrame;
        this.recordSale = recordSale;

        try {
            // Get all existing order IDs using a stream
            List<Integer> orderIds = getAllOrders().stream()
                    .map(Order::getId)
                    .collect(Collectors.toList());

            // Generate the next available ID
            newOrderId = Helpers.generateNextAvailableId(orderIds);
            
            // Update Order ID label
            orderIDLabel.setText(String.format("%03d", newOrderId));
            
        } catch (ApplicationError e) {
            Messages.showError(this, "Application Error", "An unexpected error has occurred while generating a new Order ID");
        }
    }
    
    private void showItemSearchModal() {
        JDialog dialog = new JDialog(parentFrame, "Search Items", true);
        dialog.getContentPane().add(new SearchItemDialog(item -> {
            setOrderItem(item);
            dialog.setVisible(false);
        }));
        dialog.pack();
        dialog.setLocationRelativeTo(parentFrame);
        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemNameTitle = new javax.swing.JLabel();
        searchBar = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        productName = new javax.swing.JLabel();
        dialogTitle = new javax.swing.JLabel();
        itemQuantitySelector = new javax.swing.JPanel();
        quantityDecrementBtn = new javax.swing.JButton();
        quantityIncrementBtn = new javax.swing.JButton();
        orderQuantityInput = new javax.swing.JTextField();
        itemQuantityTitle = new javax.swing.JLabel();
        recordSaleBtn = new javax.swing.JButton();
        orderSummaryPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        orderIDLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));

        itemNameTitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        itemNameTitle.setForeground(new java.awt.Color(66, 66, 66));
        itemNameTitle.setText("Item name");

        searchBar.setBackground(new java.awt.Color(255, 255, 255));
        searchBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 11, 21), 1, true));
        searchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBarMouseClicked(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(97, 11, 21));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/search_icon.png"))); // NOI18N
        searchBtn.setBorder(null);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        productName.setBackground(new java.awt.Color(204, 204, 204));
        productName.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        productName.setForeground(new java.awt.Color(204,204,204));
        productName.setText("Search and select an item to add...");

        javax.swing.GroupLayout searchBarLayout = new javax.swing.GroupLayout(searchBar);
        searchBar.setLayout(searchBarLayout);
        searchBarLayout.setHorizontalGroup(
            searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBarLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        searchBarLayout.setVerticalGroup(
            searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(searchBarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(productName)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        dialogTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        dialogTitle.setForeground(new java.awt.Color(66, 66, 66));
        dialogTitle.setText("Add a New Sale");

        itemQuantitySelector.setBackground(new java.awt.Color(255, 255, 255));
        itemQuantitySelector.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 11, 21), 1, true));
        itemQuantitySelector.setPreferredSize(new java.awt.Dimension(295, 52));

        quantityDecrementBtn.setBackground(new java.awt.Color(97, 11, 21));
        quantityDecrementBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/minus_icon.png"))); // NOI18N
        quantityDecrementBtn.setBorder(null);
        quantityDecrementBtn.setMaximumSize(new java.awt.Dimension(52, 52));
        quantityDecrementBtn.setMinimumSize(new java.awt.Dimension(52, 52));
        quantityDecrementBtn.setPreferredSize(new java.awt.Dimension(52, 52));
        quantityDecrementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityDecrementBtnActionPerformed(evt);
            }
        });

        quantityIncrementBtn.setBackground(new java.awt.Color(97, 11, 21));
        quantityIncrementBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/add_icon.png"))); // NOI18N
        quantityIncrementBtn.setBorder(null);
        quantityIncrementBtn.setMaximumSize(new java.awt.Dimension(52, 52));
        quantityIncrementBtn.setMinimumSize(new java.awt.Dimension(52, 52));
        quantityIncrementBtn.setPreferredSize(new java.awt.Dimension(52, 52));
        quantityIncrementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityIncrementBtnActionPerformed(evt);
            }
        });

        orderQuantityInput.setBackground(new java.awt.Color(255, 255, 255));
        orderQuantityInput.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        orderQuantityInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        orderQuantityInput.setText("1");
        orderQuantityInput.setBorder(null);
        orderQuantityInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                orderQuantityInputKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout itemQuantitySelectorLayout = new javax.swing.GroupLayout(itemQuantitySelector);
        itemQuantitySelector.setLayout(itemQuantitySelectorLayout);
        itemQuantitySelectorLayout.setHorizontalGroup(
            itemQuantitySelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemQuantitySelectorLayout.createSequentialGroup()
                .addComponent(quantityDecrementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderQuantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityIncrementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        itemQuantitySelectorLayout.setVerticalGroup(
            itemQuantitySelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quantityDecrementBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(quantityIncrementBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemQuantitySelectorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderQuantityInput)
                .addContainerGap())
        );

        itemQuantityTitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        itemQuantityTitle.setForeground(new java.awt.Color(66, 66, 66));
        itemQuantityTitle.setText("Quantity");

        recordSaleBtn.setBackground(new java.awt.Color(97, 11, 21));
        recordSaleBtn.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        recordSaleBtn.setForeground(new java.awt.Color(204,204,204)
        );
        recordSaleBtn.setText("Record Sale");
        recordSaleBtn.setBorder(null);
        recordSaleBtn.setMaximumSize(new java.awt.Dimension(52, 52));
        recordSaleBtn.setMinimumSize(new java.awt.Dimension(52, 52));
        recordSaleBtn.setPreferredSize(new java.awt.Dimension(52, 52));
        recordSaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordSaleBtnActionPerformed(evt);
            }
        });

        orderSummaryPanel.setBackground(new java.awt.Color(255, 255, 255));
        orderSummaryPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(97, 11, 21)));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 66, 66));
        jLabel1.setText("Order ID");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 66, 66));
        jLabel2.setText("Total amount");

        totalAmountLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        totalAmountLabel.setForeground(new java.awt.Color(66, 66, 66));
        totalAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalAmountLabel.setText("0 LKR");

        orderIDLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        orderIDLabel.setForeground(new java.awt.Color(66, 66, 66));
        orderIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        orderIDLabel.setText("000");

        javax.swing.GroupLayout orderSummaryPanelLayout = new javax.swing.GroupLayout(orderSummaryPanel);
        orderSummaryPanel.setLayout(orderSummaryPanelLayout);
        orderSummaryPanelLayout.setHorizontalGroup(
            orderSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderSummaryPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(orderSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orderIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        orderSummaryPanelLayout.setVerticalGroup(
            orderSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderSummaryPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(orderSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orderIDLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, orderSummaryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(orderSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(totalAmountLabel))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dialogTitle)
                    .addComponent(itemNameTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemQuantityTitle)
                            .addComponent(itemQuantitySelector, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderSummaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recordSaleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(dialogTitle)
                .addGap(40, 40, 40)
                .addComponent(itemNameTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(itemQuantityTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemQuantitySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(orderSummaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(recordSaleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Event: When order quantity decrement button is clicked
    private void quantityDecrementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityDecrementBtnActionPerformed
        setOrderQuantity(orderQuantity - 1);
    }//GEN-LAST:event_quantityDecrementBtnActionPerformed

    // Event: When order quantity increment button is clicked
    private void quantityIncrementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityIncrementBtnActionPerformed
        setOrderQuantity(orderQuantity + 1);
    }//GEN-LAST:event_quantityIncrementBtnActionPerformed

    private void orderQuantityInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orderQuantityInputKeyReleased
        try {
            int qty = Integer.parseInt(orderQuantityInput.getText());
            
            // Minimum allowed order quantity is 1
            if(qty < 1) {
                // Restore previous order quantity
                orderQuantityInput.setText(orderQuantity.toString());
                
                // Display an error message
                Messages.showError(this, "Input Error", "Minimum allowed number of items per order is 1");
                
                return;
            }
            
            // Update the order quantity value
            orderQuantity = qty;
        }

        // If the entered value isn't numeric
        catch(NumberFormatException e) {
            Messages.showError(this, "Input Error", "Please enter a numeric value as the quantity");
            
            // Restore previous order quantity
            orderQuantityInput.setText(orderQuantity.toString());
        }
    }//GEN-LAST:event_orderQuantityInputKeyReleased

    // Event: When the record sale button is clicked
    private void recordSaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordSaleBtnActionPerformed
        // If no item is selected to order
        if(orderItem == null) {
            Messages.showError(this, "No Item Found", "No item is selected. Please click the search button and add an item");
            return;
        }
        
        try {
            // Prepare order data to be added
            Order newOrder = new Order(newOrderId, new Date(), orderItem.getName(), orderItem.getPrice(), orderQuantity, orderItem.getPrice() * orderQuantity);
            
            // Add it to the list of orders
            OrderService.saveOrderData(newOrder);
        }
        
        catch(Exception e) {
            Messages.showError(parentFrame, "Application Error", "An unexpected error has been occured while trying to save order data");
            
            e.printStackTrace();
        }

        recordSale.run();
    }//GEN-LAST:event_recordSaleBtnActionPerformed

    // Event: When the search item button is clicked
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        showItemSearchModal();
    }//GEN-LAST:event_searchBtnActionPerformed

    // Event: When anywhere else within the search bar is clicked
    private void searchBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarMouseClicked
        showItemSearchModal();
    }//GEN-LAST:event_searchBarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dialogTitle;
    private javax.swing.JLabel itemNameTitle;
    private javax.swing.JPanel itemQuantitySelector;
    private javax.swing.JLabel itemQuantityTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel orderIDLabel;
    private javax.swing.JTextField orderQuantityInput;
    private javax.swing.JPanel orderSummaryPanel;
    private javax.swing.JLabel productName;
    private javax.swing.JButton quantityDecrementBtn;
    private javax.swing.JButton quantityIncrementBtn;
    private javax.swing.JButton recordSaleBtn;
    private javax.swing.JPanel searchBar;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel totalAmountLabel;
    // End of variables declaration//GEN-END:variables
}
