package dev.shanuka.thesweetcupcakeshop.view.panels.dashboard;

import dev.shanuka.thesweetcupcakeshop.exception.ApplicationError;
import dev.shanuka.thesweetcupcakeshop.exception.NotFoundError;
import dev.shanuka.thesweetcupcakeshop.model.Category;
import dev.shanuka.thesweetcupcakeshop.service.InventoryService;
import dev.shanuka.thesweetcupcakeshop.util.ButtonCellEditor;
import dev.shanuka.thesweetcupcakeshop.util.ButtonRenderer;
import dev.shanuka.thesweetcupcakeshop.util.Fonts;
import dev.shanuka.thesweetcupcakeshop.util.Helpers;
import dev.shanuka.thesweetcupcakeshop.util.Messages;
import dev.shanuka.thesweetcupcakeshop.view.panels.dashboard.dialogs.AddCategoryDialog;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 * Categories panel of user dashboard
 *
 * @author Shanuka
 */
public class CategoriesPanel extends javax.swing.JPanel {

    // Parent frame in which the current panel is mounted
    private final JFrame parentFrame;

    /**
     * Creates new form CategoriesPanel
     *
     * @param parentFrame Parent frame (for displaying dialogs)
     */
    public CategoriesPanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();

        // Format the categories table
        Helpers.formatTable(categoriesTable);
        // Load the list of categories
        try {
            updateCategoriesList();
        } catch (ApplicationError e) {
            Messages.showError(this, "Application Error", "An error has been occured while loading the list of categories");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        manageCategoriesLabel = new javax.swing.JLabel();
        categoriesPanel = new javax.swing.JPanel();
        categoriesTitle = new javax.swing.JLabel();
        categoriesTablePanel = new javax.swing.JPanel();
        categoriesScrollPane = new javax.swing.JScrollPane();
        categoriesTable = new javax.swing.JTable();
        addCategoryBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 244, 244));

        mainPanel.setBackground(new java.awt.Color(244, 244, 244));
        mainPanel.setMaximumSize(new java.awt.Dimension(1213, 900));
        mainPanel.setMinimumSize(new java.awt.Dimension(1213, 900));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        manageCategoriesLabel.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        manageCategoriesLabel.setForeground(new java.awt.Color(66, 66, 66));
        manageCategoriesLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageCategoriesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/manage_sales/sale_icon.png"))); // NOI18N
        manageCategoriesLabel.setText("Manage Categories");
        manageCategoriesLabel.setToolTipText("");
        manageCategoriesLabel.setAlignmentY(0.0F);
        manageCategoriesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 70, 50, 0);
        mainPanel.add(manageCategoriesLabel, gridBagConstraints);

        categoriesPanel.setBackground(new java.awt.Color(255, 255, 255));
        categoriesPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        categoriesPanel.setPreferredSize(new java.awt.Dimension(1140, 528));

        categoriesTitle.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        categoriesTitle.setForeground(new java.awt.Color(125, 125, 125));
        categoriesTitle.setText("Categories");

        categoriesTablePanel.setBackground(new java.awt.Color(255, 255, 255));
        categoriesTablePanel.setPreferredSize(new java.awt.Dimension(1070, 470));
        categoriesTablePanel.setLayout(new java.awt.BorderLayout());

        categoriesScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        categoriesScrollPane.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        categoriesScrollPane.setDoubleBuffered(true);

        categoriesTable.setFont(Fonts.robotoRegular.deriveFont(16f));
        categoriesTable.setForeground(new java.awt.Color(66, 66, 66));
        categoriesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category ID", "Category Name", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        categoriesTable.setRowHeight(40);
        categoriesTable.setSelectionBackground(new java.awt.Color(246, 246, 246));
        categoriesTable.setSelectionForeground(new java.awt.Color(66, 66, 66));
        categoriesScrollPane.setViewportView(categoriesTable);

        categoriesTablePanel.add(categoriesScrollPane, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout categoriesPanelLayout = new javax.swing.GroupLayout(categoriesPanel);
        categoriesPanel.setLayout(categoriesPanelLayout);
        categoriesPanelLayout.setHorizontalGroup(
            categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoriesTitle)
                    .addComponent(categoriesTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        categoriesPanelLayout.setVerticalGroup(
            categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(categoriesTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categoriesTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(categoriesPanel, gridBagConstraints);

        addCategoryBtn.setBackground(new java.awt.Color(154, 2, 21));
        addCategoryBtn.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        addCategoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        addCategoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/manage_categories/category_icon.png"))); // NOI18N
        addCategoryBtn.setText("Add Category");
        addCategoryBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(154, 2, 21), 1, true));
        addCategoryBtn.setIconTextGap(6);
        addCategoryBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        addCategoryBtn.setMaximumSize(new java.awt.Dimension(155, 50));
        addCategoryBtn.setMinimumSize(new java.awt.Dimension(155, 50));
        addCategoryBtn.setPreferredSize(new java.awt.Dimension(170, 50));
        addCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        mainPanel.add(addCategoryBtn, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1213, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {
        JDialog dialog = new JDialog(parentFrame, "Add Category", true);
        dialog.setResizable(false);
        dialog.getContentPane().add(new AddCategoryDialog(() -> {
            try {
                updateCategoriesList(); // Refresh the categories list
            } catch (ApplicationError e) {
                Messages.showError(this, "Application Error", "An error has been occured while refreshing the categories list");
            }
            
            dialog.dispose(); // Close the dialog and release resources
        }));
        dialog.pack();
        dialog.setLocationRelativeTo(parentFrame);
        dialog.setVisible(true);
    }

    /**
     * Clears all rows from the categories table and safely restores the button renderer and editor for the last column
     */
    private void clearCategoriesTable() {
        // Create a fresh model with the same columns
        DefaultTableModel emptyModel = new DefaultTableModel(
                new Object[]{"ID", "Name", ""}, 0
        ) {
            // Make the Actions column non editable except for the button
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2; // Only the "Actions" button column is editable
            }
        };

        // Assign the new model to the table
        categoriesTable.setModel(emptyModel);

        // Set column widths
        categoriesTable.getColumnModel().getColumn(0).setPreferredWidth(40); // Category ID
        categoriesTable.getColumnModel().getColumn(1).setPreferredWidth(800); // Category Name
        
        // Restore button renderer and editor
        categoriesTable.getColumnModel().getColumn(2).setCellRenderer(new ButtonRenderer());
        categoriesTable.getColumnModel().getColumn(2).setCellEditor(new ButtonCellEditor());
    }

    /**
     * Updates the categories table
     */
    private void updateCategoriesList() throws ApplicationError {
        clearCategoriesTable();

        List<Category> categories = InventoryService.getAllCategories();

        for (Category category : categories) {
            addCategoryToTable(category);
        }
    }

    private void handleCategoryDeleteById(int categoryId) {
        try {
            System.out.println("Attempting to delete the category with id: " + categoryId);
            String deletedCategory = InventoryService.removeCategory(categoryId);
            SwingUtilities.invokeLater(() -> {
                try {
                    updateCategoriesList();
                } catch (ApplicationError ex) {
                    Messages.showError(this, "Application Error", "Unable to refresh category list");
                }
            });
        } catch (ApplicationError | NotFoundError ex) {
            Messages.showError(this, "Application Error", "An unexpected error occurred while deleting the category");
        }
    }

    /**
     * Adds a new category to the table.
     */
    private void addCategoryToTable(Category category) {
        // Get the table's model
        DefaultTableModel model = (DefaultTableModel) categoriesTable.getModel();

        // Format the ID (makes it three digit)
        String formattedID = String.format("%03d", category.getId());

        // Create the delete category button
        JButton deleteBtn = new JButton();
        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/manage_items/delete_item.png")));
        deleteBtn.setBorder(null);
        deleteBtn.setPreferredSize(new java.awt.Dimension(28, 28));

        // Click event for the button
        deleteBtn.addActionListener((ActionEvent e) -> handleCategoryDeleteById(category.getId()));

        // Create the data row with the formatted strings and delete item button
        Object[] rowData = new Object[]{
            formattedID,
            category.getName(),
            deleteBtn
        };

        // Add the row to the model
        model.addRow(rowData);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCategoryBtn;
    private javax.swing.JPanel categoriesPanel;
    private javax.swing.JScrollPane categoriesScrollPane;
    private javax.swing.JTable categoriesTable;
    private javax.swing.JPanel categoriesTablePanel;
    private javax.swing.JLabel categoriesTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel manageCategoriesLabel;
    // End of variables declaration//GEN-END:variables
}
