package dev.shanuka.thesweetcupcakeshop.view.panels.dashboard;

import dev.shanuka.thesweetcupcakeshop.util.Fonts;

/**
 *
 * @author Shanuka
 */
public class SalesPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesPanel
     */
    public SalesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        manageSalesLabel = new javax.swing.JLabel();
        recentSales = new javax.swing.JPanel();
        recentSalesTitle = new javax.swing.JLabel();
        recentSalesTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        recentOrdersTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 244, 244));
        setMaximumSize(new java.awt.Dimension(1213, 900));
        setMinimumSize(new java.awt.Dimension(1213, 900));
        setPreferredSize(new java.awt.Dimension(1213, 900));
        setLayout(new java.awt.GridBagLayout());

        manageSalesLabel.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        manageSalesLabel.setForeground(new java.awt.Color(66, 66, 66));
        manageSalesLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageSalesLabel.setText("Manage Sales");
        manageSalesLabel.setToolTipText("");
        manageSalesLabel.setAlignmentY(0.0F);
        manageSalesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 70, 50, 0);
        add(manageSalesLabel, gridBagConstraints);
        manageSalesLabel.getAccessibleContext().setAccessibleName("Manage Sales");

        recentSales.setBackground(new java.awt.Color(255, 255, 255));
        recentSales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        recentSales.setPreferredSize(new java.awt.Dimension(1140, 528));

        recentSalesTitle.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        recentSalesTitle.setForeground(new java.awt.Color(125, 125, 125));
        recentSalesTitle.setText("Recent Sales");

        recentSalesTable.setBackground(new java.awt.Color(255, 255, 255));
        recentSalesTable.setPreferredSize(new java.awt.Dimension(1070, 470));
        recentSalesTable.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setDoubleBuffered(true);

        recentOrdersTable.setFont(Fonts.robotoRegular.deriveFont(16f));
        recentOrdersTable.setForeground(new java.awt.Color(66, 66, 66));
        recentOrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Date", "Item", "Item Price", "Quantity", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        recentOrdersTable.setRowHeight(40);
        recentOrdersTable.setSelectionBackground(new java.awt.Color(246, 246, 246));
        recentOrdersTable.setSelectionForeground(new java.awt.Color(66, 66, 66));
        jScrollPane2.setViewportView(recentOrdersTable);

        recentSalesTable.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout recentSalesLayout = new javax.swing.GroupLayout(recentSales);
        recentSales.setLayout(recentSalesLayout);
        recentSalesLayout.setHorizontalGroup(
            recentSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recentSalesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(recentSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recentSalesTitle)
                    .addComponent(recentSalesTable, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        recentSalesLayout.setVerticalGroup(
            recentSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recentSalesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(recentSalesTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recentSalesTable, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(recentSales, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(154, 2, 21));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Record Sale");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(154, 2, 21), 1, true));
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setPreferredSize(new java.awt.Dimension(140, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        add(jButton1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel manageSalesLabel;
    private javax.swing.JTable recentOrdersTable;
    private javax.swing.JPanel recentSales;
    private javax.swing.JPanel recentSalesTable;
    private javax.swing.JLabel recentSalesTitle;
    // End of variables declaration//GEN-END:variables
}
