/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.shanuka.thesweetcupcakeshop.view.panels.components;

/**
 *
 * @author Shanuka
 */
public class Sale extends javax.swing.JPanel {

    /**
     * Creates new form RecentSale
     */
    public Sale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelOrderDate = new javax.swing.JLabel();
        labelOrderNo = new javax.swing.JLabel();
        labelOrderItem = new javax.swing.JLabel();
        labelQty = new javax.swing.JLabel();
        labelTotalAmount = new javax.swing.JLabel();
        labelItemPrice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1070, 40));
        setMinimumSize(new java.awt.Dimension(1070, 40));
        setPreferredSize(new java.awt.Dimension(1070, 470));

        labelOrderDate.setBackground(new java.awt.Color(66, 66, 66));
        labelOrderDate.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        labelOrderDate.setForeground(new java.awt.Color(66, 66, 66));
        labelOrderDate.setText("Date");

        labelOrderNo.setBackground(new java.awt.Color(66, 66, 66));
        labelOrderNo.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        labelOrderNo.setForeground(new java.awt.Color(66, 66, 66));
        labelOrderNo.setText("Order No");

        labelOrderItem.setBackground(new java.awt.Color(66, 66, 66));
        labelOrderItem.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        labelOrderItem.setForeground(new java.awt.Color(66, 66, 66));
        labelOrderItem.setText("Item");

        labelQty.setBackground(new java.awt.Color(66, 66, 66));
        labelQty.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        labelQty.setForeground(new java.awt.Color(66, 66, 66));
        labelQty.setText("Quantity");

        labelTotalAmount.setBackground(new java.awt.Color(66, 66, 66));
        labelTotalAmount.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        labelTotalAmount.setForeground(new java.awt.Color(66, 66, 66));
        labelTotalAmount.setText("Total Amount");

        labelItemPrice.setBackground(new java.awt.Color(66, 66, 66));
        labelItemPrice.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        labelItemPrice.setForeground(new java.awt.Color(66, 66, 66));
        labelItemPrice.setText("Item Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelOrderItem, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelQty, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelOrderNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelOrderItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelQty)
                        .addComponent(labelTotalAmount))
                    .addComponent(labelOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelItemPrice;
    private javax.swing.JLabel labelOrderDate;
    private javax.swing.JLabel labelOrderItem;
    private javax.swing.JLabel labelOrderNo;
    private javax.swing.JLabel labelQty;
    private javax.swing.JLabel labelTotalAmount;
    // End of variables declaration//GEN-END:variables
}
